name: Build

on:
  push:
    branches:
      - build

jobs:
  job:
    env:
      BUILD_TYPE: "RelWithDebInfo"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: vs
        run: vcvarsall.bat x64
      - name: show_env
        run: echo VS150COMNTOOLS=$VS150COMNTOOLS
        shell: bash
      - name: build
        run: ./scripts/windows/build.sh
        shell: bash
  
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: |
            ${{ runner.workspace }}/**/*.dll
            ${{ runner.workspace }}/**/*.lib
            ${{ runner.workspace }}/**/*.exe
      - name: Archive logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs-${{ matrix.os }}
          path: |
            ${{ runner.workspace }}/**/CMakeOutput.log
            ${{ runner.workspace }}/**/CMakeError.log
            ${{ runner.workspace }}/**/stdout.log
            ${{ runner.workspace }}/**/stderr.log
            ${{ runner.workspace }}/**/bootstrap.log
